server {
    listen ${PORT};
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        add_header Pragma "no-cache";
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|svg|webp|ico|pdf)$ {
        expires 1h;
        add_header Cache-Control "public, immutable";
    }
}
