server {
    listen ${PORT:-8080};
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
    # Serve large static files efficiently
    location ~* \.(html|css|js|jpg|jpeg|png|gif|pdf)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
